[package]
name = "booth"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"

once_cell = "1.5"
anyhow = "1.0.44"

glib = "0.14.8"
gio = "0.14.8"
gst = { version = "0.17.4", package = "gstreamer" }

chrono = "0.4.19"
