name: Unit Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake8:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - run: pip install flake8
      - run: flake8 --ignore E402 --max-line-length=99 --show-source --statistics .

  mypy:
    name: Static Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - run: |
          sudo apt update -y
          sudo apt -y install mypy
      - run: mypy --ignore-missing-imports --disallow-incomplete-defs --pretty .

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
